<p class="featured-products">Featured Products</p>
<div class="regular">
    <div>
        <div class="slider-image-gemini">
            <img
                src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_dWHo770zN_sIDIsOne4EATqPICW7kJkL5VXCOzwR8A2c7FEC-T5UOv-QhOnjO6TL0t8&usqp=CAU"/>
        </div>
        <div class="slider-description-gemini">
            <p class="slider-product-supplier">Supplier One Company</p>
            <p class="slider-product-brand">Gemini CS223</p>
            <p class="slider-product-price-gemini">$250.00</p>
        </div>
    </div>
    <div>
        <div class="slider-image-vertuo">
            <img
                src="https://content.abt.com/image.php/big-ENV155BAE.jpg?image=/images/products/BDP_Images/big-ENV155BAE.jpg&canvas=1&min_w=750&min_h=0"/>
        </div>
        <div class="slider-description-vertuo">
            <p class="slider-product-supplier">Saladplate</p>
            <p class="slider-product-brand">VertuoPlus Deluxe Bundle</p>
            <p class="slider-product-price-vertuo">$170.00</p>
        </div>
    </div>
    <div>
        <div class="slider-image-vertuo">
            <img
                src="https://content.abt.com/image.php/big-ENV155BAE.jpg?image=/images/products/BDP_Images/big-ENV155BAE.jpg&canvas=1&min_w=750&min_h=0"/>
        </div>
        <div class="slider-description-vertuo">
            <p class="slider-product-supplier">Saladplate</p>
            <p class="slider-product-brand">VertuoPlus Deluxe Bundle-Limited Edition</p>
            <p>$170.00</p>
        </div>
    </div>
    <div>
        <div class="slider-image-zenius">
            <img src="https://m.media-amazon.com/images/I/41FtCwDOhWL.jpg"/>
        </div>
        <div class="slider-description-zenius">
            <p class="slider-product-supplier">Saladplate</p>
            <p class="slider-product-brand">Zenius ZN100</p>
            <p class="slider-product-price-zenius">$50.00</p>
        </div>
    </div>
    <div>
        <div class="slider-image-gemini">
            <img
                src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_dWHo770zN_sIDIsOne4EATqPICW7kJkL5VXCOzwR8A2c7FEC-T5UOv-QhOnjO6TL0t8&usqp=CAU"/>
        </div>
        <div class="slider-description-gemini">
            <p class="slider-product-supplier">Supplier One Company</p>
            <p class="slider-product-brand">Gemini CS223</p>
            <p class="slider-product-price-gemini">$250.00</p>
        </div>
    </div>
    <div>
        <div class="slider-image-vertuo">
            <img
                src="https://content.abt.com/image.php/big-ENV155BAE.jpg?image=/images/products/BDP_Images/big-ENV155BAE.jpg&canvas=1&min_w=750&min_h=0"/>
        </div>
        <div class="slider-description-vertuo">
            <p class="slider-product-supplier">Saladplate</p>
            <p class="slider-product-brand">VertuoPlus Deluxe Bundle</p>
            <p class="slider-product-price-vertuo">$170.00</p>
        </div>
    </div>
    <div>
        <div class="slider-image-vertuo">
            <img
                src="https://content.abt.com/image.php/big-ENV155BAE.jpg?image=/images/products/BDP_Images/big-ENV155BAE.jpg&canvas=1&min_w=750&min_h=0"/>
        </div>
        <div class="slider-description-vertuo">
            <p class="slider-product-supplier">Saladplate</p>
            <p class="slider-product-brand">VertuoPlus Deluxe Bundle-Limited Edition</p>
            <p>$170.00</p>
        </div>
    </div>
    <div>
        <div class="slider-image-zenius">
            <img src="https://m.media-amazon.com/images/I/41FtCwDOhWL.jpg"/>
        </div>
        <div class="slider-description-zenius">
            <p class="slider-product-supplier">Saladplate</p>
            <p class="slider-product-brand">Zenius ZN100</p>
            <p class="slider-product-price-zenius">$50.00</p>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
  {   ".regular": {
         "slick":{
            "arrows": true,
            "infinite": true,
            "slidesToShow": 4,
            "slidesToScroll": 1,
            "responsive": [
         {
      "breakpoint": 1024,
        "settings": {
            "slidesToShow": 4,
            "slidesToScroll": 1,
            "infinite": true,
            "arrows": true
          }
        },
    {
      "breakpoint": 600,
        "settings": {
        "slidesToShow": 2,
        "slidesToScroll": 2
      }
    },
    {
      "breakpoint": 480,
        "settings": {
        "slidesToShow": 1,
        "slidesToScroll": 1
      }
    } ]
         }

      }
  }
</script>



