<div class="main-content">
    <div class="main-content-title">
        <p class="name-company">ActiveLife</p>
        <hr>
        <p class="tagline-company">Good health through smarter products</p>
    </div>
    <div class="main-content-text">
        <div class="main-content-text-left">
            <p class="guide-title">SHONA VERTUE</p>
            <p class="guide-switch">Read the PT's tips to improve your wellbeing</p>
        </div>
        <div class="main-content-text-center">
            <p class="guide-title">RELISE HEALTH</p>
            <p class="guide-switch">Understand your body with our range of at-home health assessments</p>
        </div>
        <div class="main-content-text-right">
            <p class="guide-title">PUREGYM</p>
            <p class="guide-switch">Smash your fitness goals in the UK's largest gym chain</p>
        </div>
    </div>
</div>
