<div class="footer_contact_info">

        <div class="contact-info">
            <div>
                <h4>Footer contact info</h4>
            </div>
            <div class="content-contact-info">
                <ul class="list">
                    <li class="vragen">Vragen</li>
                    <li class="contact">Contact</li>
                    <li class="telephone">+32 3 760 39 75</li>
                </ul>
            </div>

        </div>

        <div data-mage-init='{
    "collapsible":{
        "collapsible": true,
        "openedState": "active",
        "active": true
    }}'>
            <div data-role="title">
                <h4>Column 1</h4>
            </div>
            <div data-role="content">
                <ul>
                    <li>text column</li>
                    <li>text column</li>
                    <li>text column</li>
                </ul>
            </div>
        </div>

        <div data-mage-init='{
    "collapsible":{
        "collapsible": true,
        "openedState": "active",
        "active": true
    }}'>
            <div data-role="title">
                <h4>Column 2</h4>
            </div>
            <div data-role="content">
                <ul>
                    <li>text column</li>
                    <li>text column</li>
                    <li>text column</li>
                </ul>
            </div>
        </div>

        <div data-mage-init='{
    "collapsible":{
        "collapsible": true,
        "openedState": "false",
        "deactivate": true
    }}'>
            <div data-role="title">
                <h4>Column 3</h4>
            </div>
            <div data-role="content">
                <ul>
                    <li>text column</li>
                    <li>text column</li>
                    <li>text column</li>
                </ul>
            </div>
        </div>
</div>

